-- MySQL Script generated by MySQL Workbench
-- Tue Nov  8 07:49:37 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema WholesaleManagementDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema WholesaleManagementDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `WholesaleManagementDB` DEFAULT CHARACTER SET utf8 ;
USE `WholesaleManagementDB` ;

-- -----------------------------------------------------
-- Table `WholesaleManagementDB`.`Big_Box_Department_Store`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WholesaleManagementDB`.`Big_Box_Department_Store` (
  `BB_ID` INT NOT NULL,
  `BB_LOC` VARCHAR(45) NOT NULL,
  `BB_phone` VARCHAR(15) NOT NULL,
  `Store_type` VARCHAR(45) NOT NULL,
  `BB_item_barcode` INT(10) NOT NULL,
  `BB_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`BB_ID`),
  INDEX `BB_item_barcode_idx` USING BTREE (`BB_item_barcode`) VISIBLE,
  UNIQUE INDEX `BB_ID_UNIQUE` (`BB_ID` ASC) VISIBLE,
  UNIQUE INDEX `BB_LOC_UNIQUE` (`BB_LOC` ASC) VISIBLE,
  UNIQUE INDEX `BB_phone_UNIQUE` (`BB_phone` ASC) VISIBLE,
  UNIQUE INDEX `BB_item_barcode_UNIQUE` (`BB_item_barcode` ASC) VISIBLE,
  CONSTRAINT `BB_item_barcode`
    FOREIGN KEY (`BB_item_barcode`)
    REFERENCES `WholesaleManagementDB`.`Merchandise` (`barcode`)
    ON DELETE CASCADE
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WholesaleManagementDB`.`Book_Store`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WholesaleManagementDB`.`Book_Store` (
  `bookstore_ID` INT NOT NULL,
  `bookstore_LOC` VARCHAR(45) NOT NULL,
  `bookstore_phone` VARCHAR(15) NOT NULL,
  `Store_type` VARCHAR(45) NOT NULL,
  `bookstore_item_barcode` INT(10) NOT NULL,
  `bookstore_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`bookstore_ID`),
  INDEX `bookstore_item_barcode_idx` USING BTREE (`bookstore_item_barcode`) VISIBLE,
  UNIQUE INDEX `bookstore_item_barcode_UNIQUE` (`bookstore_item_barcode` ASC) VISIBLE,
  UNIQUE INDEX `bookstore_ID_UNIQUE` (`bookstore_ID` ASC) VISIBLE,
  UNIQUE INDEX `bookstore_LOC_UNIQUE` (`bookstore_LOC` ASC) VISIBLE,
  UNIQUE INDEX `bookstore_phone_UNIQUE` (`bookstore_phone` ASC) VISIBLE,
  CONSTRAINT `bookstore_item_barcode`
    FOREIGN KEY (`bookstore_item_barcode`)
    REFERENCES `WholesaleManagementDB`.`Merchandise` (`barcode`)
    ON DELETE CASCADE
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WholesaleManagementDB`.`Clothing_Store`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WholesaleManagementDB`.`Clothing_Store` (
  `clothingstore_ID` INT NOT NULL,
  `clothingstore_LOC` VARCHAR(45) NOT NULL,
  `clothingstore_phone` VARCHAR(15) NOT NULL,
  `clothingstore_EID` INT(6) NOT NULL,
  `Store_type` VARCHAR(45) NOT NULL,
  `clothingstore_item_barcode` INT(10) NOT NULL,
  `clothingstore_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`clothingstore_ID`),
  INDEX `clothingstore_item_barcode_idx` USING BTREE (`clothingstore_item_barcode`) VISIBLE,
  UNIQUE INDEX `clothingstore_ID_UNIQUE` (`clothingstore_ID` ASC) VISIBLE,
  UNIQUE INDEX `clothingstore_LOC_UNIQUE` (`clothingstore_LOC` ASC) VISIBLE,
  UNIQUE INDEX `clothingstore_phone_UNIQUE` (`clothingstore_phone` ASC) VISIBLE,
  UNIQUE INDEX `clothingstore_EID_UNIQUE` (`clothingstore_EID` ASC) VISIBLE,
  UNIQUE INDEX `clothingstore_item_barcode_UNIQUE` (`clothingstore_item_barcode` ASC) VISIBLE,
  CONSTRAINT `clothingstore_item_barcode`
    FOREIGN KEY (`clothingstore_item_barcode`)
    REFERENCES `WholesaleManagementDB`.`Merchandise` (`barcode`)
    ON DELETE CASCADE
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WholesaleManagementDB`.`Company`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WholesaleManagementDB`.`Company` (
  `Company_name` VARCHAR(45) NOT NULL,
  `Company_LOC` VARCHAR(45) NOT NULL,
  `E_ID` INT(6) NOT NULL,
  `job_title` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Company_name`),
  UNIQUE INDEX `E_ID_UNIQUE` (`E_ID` ASC) VISIBLE,
  UNIQUE INDEX `Company_LOC_UNIQUE` (`Company_LOC` ASC) VISIBLE,
  UNIQUE INDEX `Company_name_UNIQUE` (`Company_name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WholesaleManagementDB`.`Convenience_Store`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WholesaleManagementDB`.`Convenience_Store` (
  `convenienceStore_ID` INT NOT NULL,
  `convenieceStore_LOC` VARCHAR(45) NOT NULL,
  `convenienceStore_phone` VARCHAR(15) NOT NULL,
  `Store_type` VARCHAR(45) NOT NULL,
  `convenienceStore_item_barcode` INT(10) NOT NULL,
  `convenienceStore_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`convenienceStore_ID`),
  INDEX `convenienceStore_item_barcode_idx` USING BTREE (`convenienceStore_item_barcode`) VISIBLE,
  UNIQUE INDEX `convenienceStore_ID_UNIQUE` (`convenienceStore_ID` ASC) VISIBLE,
  UNIQUE INDEX `convenieceStore_LOC_UNIQUE` (`convenieceStore_LOC` ASC) VISIBLE,
  UNIQUE INDEX `convenienceStore_phone_UNIQUE` (`convenienceStore_phone` ASC) VISIBLE,
  UNIQUE INDEX `convenienceStore_item_barcode_UNIQUE` (`convenienceStore_item_barcode` ASC) VISIBLE,
  CONSTRAINT `convenienceStore_item_barcode`
    FOREIGN KEY (`convenienceStore_item_barcode`)
    REFERENCES `WholesaleManagementDB`.`Merchandise` (`barcode`)
    ON DELETE CASCADE
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WholesaleManagementDB`.`Customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WholesaleManagementDB`.`Customers` (
  `Customer_ID` INT(8) NOT NULL,
  `full_name` VARCHAR(45) CHARACTER SET 'big5' NOT NULL,
  `DOB` DATE NOT NULL,
  `age` TINYINT(3) NOT NULL,
  `Order_ID` INT(8) NOT NULL,
  `Customer_Phone` VARCHAR(15) NULL,
  PRIMARY KEY (`Customer_ID`),
  INDEX `Order_ID_idx` USING BTREE (`Order_ID`) VISIBLE,
  UNIQUE INDEX `Customer_ID_UNIQUE` (`Customer_ID` ASC) VISIBLE,
  UNIQUE INDEX `Order_ID_UNIQUE` (`Order_ID` ASC) VISIBLE,
  CONSTRAINT `Order_ID`
    FOREIGN KEY (`Order_ID`)
    REFERENCES `WholesaleManagementDB`.`Order` (`Order_ID`)
    ON DELETE CASCADE
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WholesaleManagementDB`.`Employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WholesaleManagementDB`.`Employee` (
  `E_ID` INT(6) NOT NULL,
  `full_name` VARCHAR(45) NOT NULL,
  `DOB` DATE NOT NULL,
  `age` TINYINT(3) NOT NULL,
  `job_title` VARCHAR(45) NOT NULL,
  `hourly_wage` DOUBLE NULL,
  PRIMARY KEY (`E_ID`),
  INDEX `E_ID_idx` USING BTREE (`E_ID`) VISIBLE,
  UNIQUE INDEX `E_ID_UNIQUE` (`E_ID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WholesaleManagementDB`.`Factory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WholesaleManagementDB`.`Factory` (
  `Factory_ID` INT NOT NULL,
  `Factory_LOC` VARCHAR(45) NOT NULL,
  `Factory_Phone` VARCHAR(15) NULL,
  `Factory_item_barcode` INT(10) NOT NULL,
  `Factory_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Factory_ID`),
  INDEX `Factory_item_barcode_idx` (`Factory_item_barcode` ASC) INVISIBLE,
  UNIQUE INDEX `Factory_item_barcode_UNIQUE` (`Factory_item_barcode` ASC) VISIBLE,
  UNIQUE INDEX `Factory_Phone_UNIQUE` (`Factory_Phone` ASC) VISIBLE,
  UNIQUE INDEX `Factory_LOC_UNIQUE` (`Factory_LOC` ASC) VISIBLE,
  UNIQUE INDEX `Factory_ID_UNIQUE` (`Factory_ID` ASC) VISIBLE,
  CONSTRAINT `Factory_item_barcode`
    FOREIGN KEY (`Factory_item_barcode`)
    REFERENCES `WholesaleManagementDB`.`Merchandise` (`barcode`)
    ON DELETE CASCADE
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WholesaleManagementDB`.`Farm`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WholesaleManagementDB`.`Farm` (
  `Farm_ID` INT NOT NULL,
  `Farm_LOC` VARCHAR(45) NOT NULL,
  `Farm_phone` VARCHAR(15) NOT NULL,
  `Farm_item_barcode` INT(10) NOT NULL,
  `Farm_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Farm_ID`),
  INDEX `Farm_item_barcode_idx` (`Farm_item_barcode` ASC) VISIBLE,
  UNIQUE INDEX `Farm_ID_UNIQUE` (`Farm_ID` ASC) VISIBLE,
  UNIQUE INDEX `Farm_LOC_UNIQUE` (`Farm_LOC` ASC) VISIBLE,
  UNIQUE INDEX `Farm_phone_UNIQUE` (`Farm_phone` ASC) VISIBLE,
  UNIQUE INDEX `Farm_item_barcode_UNIQUE` (`Farm_item_barcode` ASC) VISIBLE,
  CONSTRAINT `Farm_item_barcode`
    FOREIGN KEY (`Farm_item_barcode`)
    REFERENCES `WholesaleManagementDB`.`Merchandise` (`barcode`)
    ON DELETE CASCADE
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WholesaleManagementDB`.`Grocery_Store`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WholesaleManagementDB`.`Grocery_Store` (
  `GroceryStore_ID` INT(10) NOT NULL,
  `GroceryStore_LOC` VARCHAR(45) NOT NULL,
  `GroceryStore_Phone` VARCHAR(15) NOT NULL,
  `Store_type` VARCHAR(45) NOT NULL,
  `GroceryStore_item_barcode` INT(10) NOT NULL,
  `GroceryStore_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`GroceryStore_ID`),
  INDEX `GroceryStore_item_barcode_idx` USING BTREE (`GroceryStore_item_barcode`) VISIBLE,
  UNIQUE INDEX `GroceryStore_ID_UNIQUE` (`GroceryStore_ID` ASC) VISIBLE,
  UNIQUE INDEX `GroceryStore_LOC_UNIQUE` (`GroceryStore_LOC` ASC) VISIBLE,
  UNIQUE INDEX `GroceryStore_Phone_UNIQUE` (`GroceryStore_Phone` ASC) VISIBLE,
  UNIQUE INDEX `GroceryStore_item_barcode_UNIQUE` (`GroceryStore_item_barcode` ASC) VISIBLE,
  CONSTRAINT `GroceryStore_item_barcode`
    FOREIGN KEY (`GroceryStore_item_barcode`)
    REFERENCES `WholesaleManagementDB`.`Merchandise` (`barcode`)
    ON DELETE CASCADE
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WholesaleManagementDB`.`Liquor_Store`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WholesaleManagementDB`.`Liquor_Store` (
  `LiquorStore_ID` INT NOT NULL,
  `LiquorStore_LOC` VARCHAR(45) NOT NULL,
  `LiquorStore_phone` VARCHAR(15) NOT NULL,
  `Store_type` VARCHAR(45) NOT NULL,
  `LiquorStore_item_barcode` INT(10) NOT NULL,
  `LiquorStore_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`LiquorStore_ID`),
  INDEX `LiquorStore_item_barcode_idx` (`LiquorStore_item_barcode` ASC) INVISIBLE,
  UNIQUE INDEX `LiquorStore_item_barcode_UNIQUE` (`LiquorStore_item_barcode` ASC) VISIBLE,
  UNIQUE INDEX `LiquorStore_phone_UNIQUE` (`LiquorStore_phone` ASC) VISIBLE,
  UNIQUE INDEX `LiquorStore_LOC_UNIQUE` (`LiquorStore_LOC` ASC) VISIBLE,
  UNIQUE INDEX `LiquorStore_ID_UNIQUE` (`LiquorStore_ID` ASC) VISIBLE,
  CONSTRAINT `LiquorStore_item_barcode`
    FOREIGN KEY (`LiquorStore_item_barcode`)
    REFERENCES `WholesaleManagementDB`.`Merchandise` (`barcode`)
    ON DELETE CASCADE
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WholesaleManagementDB`.`Management`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WholesaleManagementDB`.`Management` (
  `E_ID` INT(6) NOT NULL,
  `full_name` VARCHAR(45) NOT NULL,
  `DOB` DATE NOT NULL,
  `age` TINYINT(3) NOT NULL,
  `salary` DOUBLE NOT NULL,
  PRIMARY KEY (`E_ID`),
  UNIQUE INDEX `E_ID_UNIQUE` (`E_ID` ASC) VISIBLE,
  CONSTRAINT `E_ID`
    FOREIGN KEY (`E_ID`)
    REFERENCES `WholesaleManagementDB`.`Employee` (`E_ID`)
    ON DELETE CASCADE
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WholesaleManagementDB`.`Manufacturer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WholesaleManagementDB`.`Manufacturer` (
  `Manufacturer_ID` INT NOT NULL,
  `Manufacturer_LOC` VARCHAR(45) NOT NULL,
  `Manufacturer_Phone` VARCHAR(15) NOT NULL,
  `Company_name` INT(10) NOT NULL,
  PRIMARY KEY (`Manufacturer_ID`),
  UNIQUE INDEX `Manufacturer_LOC_UNIQUE` (`Manufacturer_LOC` ASC) VISIBLE,
  UNIQUE INDEX `Manufacturer_Phone_UNIQUE` (`Manufacturer_Phone` ASC) VISIBLE,
  UNIQUE INDEX `Manufacturer_ID_UNIQUE` (`Manufacturer_ID` ASC) VISIBLE,
  UNIQUE INDEX `Company_name_UNIQUE` (`Company_name` ASC) VISIBLE,
  CONSTRAINT `Company_name`
    FOREIGN KEY (`Manufacturer_ID`)
    REFERENCES `WholesaleManagementDB`.`Company` (`Company_name`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WholesaleManagementDB`.`Merchandise`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WholesaleManagementDB`.`Merchandise` (
  `Merchandise_ID` INT(10) NOT NULL,
  `barcode` INT(10) NOT NULL,
  `Merchandise_type` VARCHAR(45) NOT NULL,
  `Merchandise_name` VARCHAR(45) NOT NULL,
  `price` DOUBLE NOT NULL,
  PRIMARY KEY (`Merchandise_ID`),
  UNIQUE INDEX `barcode_UNIQUE` (`barcode` ASC) VISIBLE,
  UNIQUE INDEX `Merchandise_ID_UNIQUE` (`Merchandise_ID` ASC) VISIBLE,
  CONSTRAINT `barcode`
    FOREIGN KEY (`barcode`)
    REFERENCES `WholesaleManagementDB`.`Order` (`Order_ID`)
    ON DELETE CASCADE
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WholesaleManagementDB`.`Order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WholesaleManagementDB`.`Order` (
  `Order_ID` INT(8) NOT NULL,
  `Customer_ID` INT(8) NOT NULL,
  `quantity` INT NULL,
  `barcode` INT(10) NOT NULL,
  `Merchandise_ID` INT(10) NOT NULL,
  `Merchandise_name` VARCHAR(45) NOT NULL,
  `total_amount` DOUBLE NOT NULL,
  PRIMARY KEY (`Order_ID`),
  INDEX ` Customer_ID` USING BTREE (`Customer_ID`) VISIBLE,
  UNIQUE INDEX `Order_ID_UNIQUE` (`Order_ID` ASC) VISIBLE,
  UNIQUE INDEX `Customer_ID_UNIQUE` (`Customer_ID` ASC) VISIBLE,
  UNIQUE INDEX `barcode_UNIQUE` (`barcode` ASC) VISIBLE,
  UNIQUE INDEX `Merchandise_ID_UNIQUE` (`Merchandise_ID` ASC) VISIBLE,
  CONSTRAINT `Customer_ID`
    FOREIGN KEY (`Order_ID`)
    REFERENCES `WholesaleManagementDB`.`Customers` (`Customer_ID`)
    ON DELETE CASCADE
    ON UPDATE RESTRICT,
  CONSTRAINT `Merchandise_ID`
    FOREIGN KEY (`Merchandise_ID`)
    REFERENCES `WholesaleManagementDB`.`Merchandise` (`Merchandise_ID`)
    ON DELETE CASCADE
    ON UPDATE RESTRICT,
  CONSTRAINT `barcode`
    FOREIGN KEY (`barcode`)
    REFERENCES `WholesaleManagementDB`.`Order` (`Order_ID`)
    ON DELETE CASCADE
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WholesaleManagementDB`.`Restaurants`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WholesaleManagementDB`.`Restaurants` (
  `Restaurant_ID` INT NOT NULL,
  `Restaurant_LOC` VARCHAR(45) NOT NULL,
  `Restaurant_phone` VARCHAR(15) NOT NULL,
  `Store_type` VARCHAR(45) NOT NULL,
  `Restaurants_food_ID` INT(10) NOT NULL,
  `Restaurant_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Restaurant_ID`),
  UNIQUE INDEX `Restaurant_ID_UNIQUE` (`Restaurant_ID` ASC) VISIBLE,
  UNIQUE INDEX `Restaurant_LOC_UNIQUE` (`Restaurant_LOC` ASC) VISIBLE,
  UNIQUE INDEX `Restaurant_phone_UNIQUE` (`Restaurant_phone` ASC) VISIBLE,
  UNIQUE INDEX `Restaurants_food_ID_UNIQUE` (`Restaurants_food_ID` ASC) VISIBLE,
  CONSTRAINT `Restaurant_food_ID`
    FOREIGN KEY (`Restaurants_food_ID`)
    REFERENCES `WholesaleManagementDB`.`Merchandise` (`Merchandise_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WholesaleManagementDB`.`Sport_Equiptment_Store`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WholesaleManagementDB`.`Sport_Equiptment_Store` (
  `SportsEquiptment_ID` INT NOT NULL,
  `SportsEquiptment_LOC` VARCHAR(45) NOT NULL,
  `SportsEquiptment_Phone` VARCHAR(15) NOT NULL,
  `Store_type` VARCHAR(45) NOT NULL,
  `SportsEquiptment_item_barcode` INT(10) NOT NULL,
  `SportsEquiptment_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`SportsEquiptment_ID`),
  UNIQUE INDEX `SportsEquiptment_ID_UNIQUE` (`SportsEquiptment_ID` ASC) VISIBLE,
  UNIQUE INDEX `SportsEquiptment_LOC_UNIQUE` (`SportsEquiptment_LOC` ASC) VISIBLE,
  UNIQUE INDEX `SportsEquiptment_Phone_UNIQUE` (`SportsEquiptment_Phone` ASC) VISIBLE,
  UNIQUE INDEX `SportsEquiptment_item_barcode_UNIQUE` (`SportsEquiptment_item_barcode` ASC) VISIBLE,
  CONSTRAINT `SportsEquiptment_item_barcode`
    FOREIGN KEY (`SportsEquiptment_item_barcode`)
    REFERENCES `WholesaleManagementDB`.`Merchandise` (`barcode`)
    ON DELETE CASCADE
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WholesaleManagementDB`.`Stores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WholesaleManagementDB`.`Stores` (
  `Store_ID` INT(10) NOT NULL,
  `Store_LOC` VARCHAR(45) NOT NULL,
  `Store_type` VARCHAR(45) NOT NULL)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
